In [7]:
%load_ext autoreload
%autoreload 2

import sys
from pathlib import Path

repo_root = Path.cwd().parent
sys.path.append(str(repo_root))

import src.utils.config as config
import src.utils.pdata_io as pdio

data_root, pdata_root, cc_data = pdio.load_project_context()

print(data_root)
print(pdata_root)
print("Number of animals:", len(cc_data))

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
[LOADED] Project context: /mnt/pdata/Classical_Conditioning/_cache/project_context.pkl
/mnt/data/Classical_Conditioning
/mnt/pdata/Classical_Conditioning
Number of animals: 5

In [10]:
from src.qc.qc_events import (
    build_event_qc_table,
    # build_epoch_window_table,
    save_behavior_qc_tables,
)
from src.utils.pdata_io import clean_df_for_hdf

events_df, session_summary_df = build_event_qc_table(
    cc_data,
    drop_first_n=0,
    drop_last_n=0,
    min_hab_led_on_s=None,
    min_recording_duration_s=None,
    exclude_short_sessions_from_epochs=False,
)

events_df = clean_df_for_hdf(events_df)
session_summary_df = clean_df_for_hdf(session_summary_df)

qc_file = save_behavior_qc_tables(
    events_df,
    session_summary_df,
    # windows_df,
    pdata_root=pdata_root,
    filename="behavior_QC.h5",
)

[SAVED] Behavior QC tables: /mnt/pdata/Classical_Conditioning/_cache/behavior_QC.h5

In [12]:
events_df

,animal,date,phase,event_number,on_idx,off_idx,on_time_s,off_time_s,on_duration_s,trial_forward_cm,...,valid_for_epoch_extraction,discard_reason,fs,n_samples,recording_duration_s,date_dt,rig_day_from_date,rig_session_number,phase_day_from_date,phase_session_number
0,NML_04,2026_01_12,air_training,0,0,24352,0.000000,4.870400,4.870400,6.333451,...,True,,5000.0,6544500,1308.9,2026-01-12,17,17,1,1
1,NML_04,2026_01_12,air_training,1,99782,119895,19.956400,23.979000,4.022600,5.328141,...,True,,5000.0,6544500,1308.9,2026-01-12,17,17,1,1
2,NML_04,2026_01_12,air_training,2,195327,206396,39.065399,41.279202,2.213802,5.101946,...,True,,5000.0,6544500,1308.9,2026-01-12,17,17,1,1
3,NML_04,2026_01_12,air_training,3,281824,291001,56.364799,58.200199,1.835400,5.403539,...,True,,5000.0,6544500,1308.9,2026-01-12,17,17,1,1
4,NML_04,2026_01_12,air_training,4,366433,377115,73.286598,75.422997,2.136398,5.177345,...,True,,5000.0,6544500,1308.9,2026-01-12,17,17,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5463,NML_08,2026_03_21,tone_air_training,44,5566095,5603409,1113.218994,1120.681763,7.462769,54.990438,...,True,,5000.0,6163500,1232.7,2026-03-21,48,47,10,10
5464,NML_08,2026_03_21,tone_air_training,45,5693327,5731803,1138.665405,1146.360596,7.695190,54.990438,...,True,,5000.0,6163500,1232.7,2026-03-21,48,47,10,10
5465,NML_08,2026_03_21,tone_air_training,46,5821719,5859229,1164.343750,1171.845825,7.502075,54.990438,...,True,,5000.0,6163500,1232.7,2026-03-21,48,47,10,10
5466,NML_08,2026_03_21,tone_air_training,47,5949145,5991627,1189.828979,1198.325439,8.496460,54.990438,...,True,,5000.0,6163500,1232.7,2026-03-21,48,47,10,10
5467,NML_08,2026_03_21,tone_air_training,48,6081542,6117843,1216.308350,1223.568604,7.260254,54.990438,...,True,,5000.0,6163500,1232.7,2026-03-21,48,47,10,10

In [4]:
events_df[~events_df["valid_for_epoch_extraction"]][
    [
        "animal",
        "date",
        "phase",
        "event_number",
        "on_duration_s",
        "trial_forward_cm",
        "discard_reason",
    ]
]

,animal,date,phase,event_number,on_duration_s,trial_forward_cm,discard_reason
0,NML_04,2026_01_12,air_training,0,4.870400,6.333451,edge_event_excluded
58,NML_04,2026_01_12,air_training,58,6.954468,14.652388,edge_event_excluded
59,NML_04,2026_01_13,air_training,0,21.984602,16.487078,edge_event_excluded
113,NML_04,2026_01_13,air_training,54,7.924072,7.187964,edge_event_excluded
114,NML_04,2026_01_14,air_training,0,35.012802,12.189379,edge_event_excluded
...,...,...,...,...,...,...,...
8567,NML_08,2026_03_19,tone_air_training,49,6.623535,54.990438,edge_event_excluded
8568,NML_08,2026_03_20,tone_air_training,0,2.158000,20.055928,edge_event_excluded
8615,NML_08,2026_03_20,tone_air_training,47,8.494995,54.990438,edge_event_excluded
8616,NML_08,2026_03_21,tone_air_training,0,2.594600,20.081060,edge_event_excluded
8664,NML_08,2026_03_21,tone_air_training,48,7.260254,54.990438,edge_event_excluded

In [33]:
windows_df[windows_df["phase"] == "tone_air_training"]["epoch_name"].value_counts()

epoch_name
air_off_center     1932
air_on_center      1932
tone_off_center    1932
tone_on_center     1932
Name: count, dtype: int64